# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppOfMyLife' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppOfMyLife
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.1'
  pod 'ObjectMapper', '~> 2.2'

  target 'AppOfMyLifeTests' do
      
      pod 'Quick'
      pod 'Nimble'
      pod 'Mockingjay'
      
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppOfMyLifeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
